# Generated by Django 3.0.6 on 2020-05-09 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHolderFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceholderformat', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PricePaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SharedOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Address', verbose_name='Адрес на складе')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Shop', verbose_name='Магазин')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Warehouse', verbose_name='Склад')),
            ],
        ),
        migrations.CreateModel(
            name='PricePaper',
            fields=[
                ('sharedoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bali_client.SharedOption')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Количество')),
                ('image', models.ImageField(blank=True, upload_to='images/priceholders', verbose_name='Изображение')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Format', verbose_name='Формат')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.PricePaperType', verbose_name='Тип')),
            ],
            bases=('bali_client.sharedoption',),
        ),
        migrations.CreateModel(
            name='PriceHolder',
            fields=[
                ('sharedoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bali_client.SharedOption')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Количество')),
                ('image', models.ImageField(blank=True, upload_to='images/priceholders', verbose_name='Изображение')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.PriceHolderFormat', verbose_name='Артикул')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Option', verbose_name='Дополнительные опции')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Type', verbose_name='Тип')),
            ],
            bases=('bali_client.sharedoption',),
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('sharedoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bali_client.SharedOption')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Количество')),
                ('image', models.ImageField(blank=True, upload_to='images/pockets', verbose_name='Изображение')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Format', verbose_name='Формат')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Option', verbose_name='Дополнительные опции')),
                ('orientation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Orientation', verbose_name='Ориентация')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Type', verbose_name='Тип')),
            ],
            bases=('bali_client.sharedoption',),
        ),
    ]
