# Generated by Django 3.0.6 on 2020-05-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OtherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlasticHolderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PlasticHolderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='pricepaper',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/pricepapers', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='PlasticHolder',
            fields=[
                ('sharedoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bali_client.SharedOption')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Количество')),
                ('image', models.ImageField(blank=True, upload_to='images/plasticholders', verbose_name='Изображение')),
                ('orientation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Orientation', verbose_name='Ориентация')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.PlasticHolderPosition', verbose_name='Размещение')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.PlasticHolderType', verbose_name='Тип')),
            ],
            bases=('bali_client.sharedoption',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('sharedoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bali_client.SharedOption')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Количество')),
                ('image', models.ImageField(blank=True, upload_to='images/others', verbose_name='Изображение')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.OtherName', verbose_name='Наименование')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.OtherType', verbose_name='Тип')),
            ],
            bases=('bali_client.sharedoption',),
        ),
    ]
