# Generated by Django 3.0.6 on 2020-05-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0002_auto_20200509_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plasticholderposition',
            name='position',
            field=models.CharField(max_length=15, verbose_name='Размещение'),
        ),
        migrations.AlterField(
            model_name='plasticholdertype',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Тип'),
        ),
    ]
