# Generated by Django 3.0.6 on 2020-05-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0002_auto_20200508_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='option',
            field=models.ForeignKey(blank=True, default='без опций', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.PocketOption'),
        ),
    ]
