# Generated by Django 3.0.6 on 2020-05-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0004_auto_20200509_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Складской адрес', 'verbose_name_plural': 'Складские адреса'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Формат бумаги (включая нестандартные)', 'verbose_name_plural': 'Форматы бумаги (включая нестандартные)'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Дополнительные опции (доп. карманы, размеры доп. карманов, габариты)', 'verbose_name_plural': 'Дополнительная опция (карман, размер и т.д.)'},
        ),
        migrations.AlterModelOptions(
            name='orientation',
            options={'verbose_name': 'Ориентация бумаги', 'verbose_name_plural': 'Ориентации бумаги'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': 'Прочее', 'verbose_name_plural': 'Прочее'},
        ),
        migrations.AlterModelOptions(
            name='othername',
            options={'verbose_name': 'Прочее - полное наименование', 'verbose_name_plural': 'Прочее - полные наименования'},
        ),
        migrations.AlterModelOptions(
            name='othertype',
            options={'verbose_name': 'Прочее - тип', 'verbose_name_plural': 'Прочее - типы'},
        ),
        migrations.AlterModelOptions(
            name='plasticholder',
            options={'verbose_name': 'Пластиковый держатель', 'verbose_name_plural': 'Пластиковые держатели'},
        ),
        migrations.AlterModelOptions(
            name='plasticholderposition',
            options={'verbose_name': 'Тип размещения пластикового держателя', 'verbose_name_plural': 'Типы размещений пластиковых держателей'},
        ),
        migrations.AlterModelOptions(
            name='plasticholdertype',
            options={'verbose_name': 'Тип пластикового держателя', 'verbose_name_plural': 'Типы пластиковых держателей'},
        ),
        migrations.AlterModelOptions(
            name='pocket',
            options={'verbose_name': 'Карман', 'verbose_name_plural': 'Карманы'},
        ),
        migrations.AlterModelOptions(
            name='priceholder',
            options={'verbose_name': 'Ценникодержатель', 'verbose_name_plural': 'Ценникодержатели'},
        ),
        migrations.AlterModelOptions(
            name='priceholderformat',
            options={'verbose_name': 'Формат ценникодержателя', 'verbose_name_plural': 'Форматы ценникодержателей (DBR20, DBR60 и т.д.)'},
        ),
        migrations.AlterModelOptions(
            name='pricepaper',
            options={'verbose_name': 'Бумага для ценников', 'verbose_name_plural': 'Бумага для ценников'},
        ),
        migrations.AlterModelOptions(
            name='pricepapertype',
            options={'verbose_name': 'Тип бумаги для ценников', 'verbose_name_plural': 'Типы бумаги для ценников'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Номер магазина', 'verbose_name_plural': 'Номера магазинов'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterField(
            model_name='priceholder',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.PriceHolderFormat', verbose_name='Формат'),
        ),
    ]
