# Generated by Django 3.0.6 on 2020-06-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticHolderFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10, verbose_name='Формат')),
            ],
        ),
        migrations.AlterField(
            model_name='plasticholderorientation',
            name='orientation',
            field=models.CharField(max_length=14, verbose_name='Ориентация'),
        ),
        migrations.AlterField(
            model_name='priceholderheight',
            name='height',
            field=models.CharField(max_length=10, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='priceholderwight',
            name='widht',
            field=models.CharField(max_length=10, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='plasticholder',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.PlasticHolderFormat', verbose_name='Формат'),
        ),
    ]
