# Generated by Django 3.0.6 on 2020-06-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0002_auto_20200602_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plasticholderformat',
            options={'verbose_name': 'Формат', 'verbose_name_plural': 'Форматы'},
        ),
    ]
