# Generated by Django 3.0.7 on 2020-07-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0006_writeoffmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeoffmaterial',
            options={'verbose_name': 'Списанный материал', 'verbose_name_plural': 'Списанные материалы'},
        ),
    ]
