# Generated by Django 3.0.6 on 2020-05-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0007_auto_20200522_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocket',
            name='cart_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='В корзине'),
        ),
    ]
