# Generated by Django 3.0.6 on 2020-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0008_pocket_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='cart_count',
            field=models.SmallIntegerField(default=0, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='other',
            name='cart_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Доступно для списания'),
        ),
        migrations.AddField(
            model_name='plasticholder',
            name='cart_count',
            field=models.SmallIntegerField(default=0, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='plasticholder',
            name='cart_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Доступно для списания'),
        ),
        migrations.AddField(
            model_name='pocket',
            name='cart_count',
            field=models.SmallIntegerField(default=0, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='priceholder',
            name='cart_count',
            field=models.SmallIntegerField(default=0, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='priceholder',
            name='cart_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Доступно для списания'),
        ),
        migrations.AddField(
            model_name='pricepaper',
            name='cart_count',
            field=models.SmallIntegerField(default=0, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='pricepaper',
            name='cart_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Доступно для списания'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='cart_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Доступно для списания'),
        ),
    ]
