# Generated by Django 3.0.7 on 2020-07-07 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0008_auto_20200707_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoffmaterial',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время списания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='writeoffmaterial',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата списания'),
        ),
    ]
