# Generated by Django 3.0.7 on 2020-07-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bali_client', '0011_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bali_client.Shop', verbose_name='Магазин'),
        ),
    ]
